matrix:
  include:
    - os: osx
      name: 🍏 Clang
      osx_image: xcode9.4

before_install:
  - brew install plenv
  - brew install perl-build
  - eval "$(plenv init -)"

script:
  - ls -al /usr/local/bin/
  - realink -f /usr/local/bin/perl-build
  - cat /usr/local/bin/perl-build
  - perl-build --version
  - ls -al $(plenv root)
  - ls -al $(plenv root)/plugins
  - plenv install 5.28.0
  - plenv install --list
